# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Simulator
                                 A QGIS plugin
 This plugin similaté the agent's movements.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-10
        copyright            : (C) 2021 by HCMUT
        email                : duc.nguyenquang@hcmut.edu.vn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Simulator class from file Simulator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .simulator import Simulator
    return Simulator(iface)
